  <?php
    include_once("./PHPMailer.php");
    include_once("./SMTP.php");
    include_once("./Exception.php");

    $mail = new PHPMailer\PHPMailer\PHPMailer();
    $mail->isSMTP();

    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\SMTP;
    use PHPMailer\PHPMailer\Exception;

    $mail = new PHPMailer(true);

    //Server settings
    /* $mail->SMTPDebug = SMTP::DEBUG_SERVER;       */
    if (isset($_POST['email'])) {               //Enable verbose debug output
        $mail->isSMTP();                                            //Send using SMTP
        $mail->Host       = 'smtp.gmail.com';                     //Set the SMTP server to send through
        $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
        $mail->Username   = 'arzeljrz17@gmail.com';                     //SMTP username
        $mail->Password   = 'rffsqyrbbhygwnco';                               //SMTP password
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption
        $mail->Port       = 465;                                    //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`

        //Recipients
        $mail->setFrom('arzeljrz@gmail.com', 'Arzel John Zolina');
        $mail->addAddress('cypheruhrzel@gmail.com', 'cypheruhrzel ');
        $mail->addAddress('lastimosoarnie@gmail.com', 'Arnie Lastimoso');
        $mail->addAddress('renzrajahbuayan@gmail.com', 'Hamdawe Esmael');
        $mail->addAddress('montanomarjorie9@gmail.com', 'Marjorie Montaño');
        $mail->addAddress('ar.ar.rivamonte.10@gmail.com', 'Ariel Nalagon Rivamonte');
        $mail->addAddress('pingoyzyra123@gmail.com', 'Zyra Pingoy');
        $mail->addAddress('jorefmarzon28@gmail.com', 'Jorefe Dagangon Marzon');

        //Name is option

        //Attachments
        $mail->addAttachment('../db/payrolldb.sql');
        $mail->Subject = "Database Back Up";
        $mail->Body = "<i>This is a system generated by email.\n please secure this incase of need.</i>";
        $mail->AltBody = "This is the plain text version of the email content";

        if ($mail->send()) {
            echo '<script>alert("Email Backup successfully generated!")</script>';
        } else {
            echo "message cannot be sent";
        }
    }
    ?>
  <?php include 'includes/session.php'; ?>
  <?php include 'includes/header.php'; ?>
  <style>
      .button-30 {
          align-items: center;
          appearance: none;
          background-color: #FCFCFD;
          border-radius: 4px;
          border-width: 0;
          box-shadow: rgba(45, 35, 66, 0.4) 0 2px 4px, rgba(45, 35, 66, 0.3) 0 7px 13px -3px, #D6D6E7 0 -3px 0 inset;
          box-sizing: border-box;
          color: #36395A;
          cursor: pointer;
          display: inline-flex;
          font-family: "JetBrains Mono", monospace;
          height: 48px;
          justify-content: center;
          line-height: 1;
          list-style: none;
          overflow: hidden;
          padding-left: 16px;
          padding-right: 16px;
          position: relative;
          text-align: left;
          text-decoration: none;
          transition: box-shadow .15s, transform .15s;
          user-select: none;
          -webkit-user-select: none;
          touch-action: manipulation;
          white-space: nowrap;
          will-change: box-shadow, transform;
          font-size: 18px;
      }

      .button-30:focus {
          box-shadow: #D6D6E7 0 0 0 1.5px inset, rgba(45, 35, 66, 0.4) 0 2px 4px, rgba(45, 35, 66, 0.3) 0 7px 13px -3px, #D6D6E7 0 -3px 0 inset;
      }

      .button-30:hover {
          box-shadow: rgba(45, 35, 66, 0.4) 0 4px 8px, rgba(45, 35, 66, 0.3) 0 7px 13px -3px, #D6D6E7 0 -3px 0 inset;
          transform: translateY(-2px);
      }

      .button-30:active {
          box-shadow: #D6D6E7 0 3px 7px inset;
          transform: translateY(2px);
      }

      body {
          font-family: 'Poppins', sans-serif;
          background-color: #141414;
          color: #1c1e21;
      }

      main {
          height: 50vh;
          width: 100vw;
          position: relative;
          margin: 0 auto;
      }


      .row {
          display: flex;
          justify-content: space-around;
          align-items: center;
          width: 100%;
          max-width: 1000px;
          position: absolute;
          left: 50%;
          top: 50%;
          transform: translate(-50%, -50%);
      }

      .col-logo {
          flex: 0 0 50%;
          text-align: left;
      }

      .col-form {
          flex: 0 0 40%;
          text-align: center;
      }

      .col-logo img {
          max-width: 300px;
      }

      .col-logo h2 {
          font: 26px;
          font-weight: 400;
          padding: 0 30px;
          line-height: 32px;
      }

      .col-form .form-container {
          background-color: #141414;
          border: none;
          border-radius: 8px;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1), 0 8px 16px rgba(0, 0, 0, 0.1);
          margin-bottom: 30px;
          padding: 20px;
          max-width: 400px;
      }

      .col-form .form-container input,
      .col-form .form-container .btn-login {
          width: 100%;
          margin: 5px 0;
          height: 45px;
          vertical-align: middle;
          font-size: 16px;
      }

      .col-form .form-container input {
          border: 1px solid #dddfe2;
          color: #1d2129;
          padding: 0 8px;
          outline: none;
      }

      .col-form .form-container input:focus {
          border-color: #1877f2;
          box-shadow: 0 0 0 2px #e7f3ff;
      }

      .col-form .form-container .btn-login {
          background-color: #1877f2;
          border: none;
          border-radius: 6px;
          font-size: 20px;
          padding: 0 16px;
          color: #ffffff;
          font-weight: 700;
      }

      .col-form .form-container a {
          display: block;
          color: #1877f2;
          font-size: 14px;
          text-decoration: none;
          padding: 10px 0 20px;
          border-bottom: 1px solid #dadde1;
      }

      .col-form .form-container a:hover {
          text-decoration: underline;
      }

      .col-form .form-container .btn-new {
          background-color: #42b72a;
          border: none;
          border-radius: 6px;
          font-size: 17px;
          line-height: 48px;
          padding: 0 16px;
          color: #ffffff;
          font-weight: 700;
          margin-top: 20px;
      }

      .col-form p {
          font-size: 14px;
      }

      .col-form p a {
          text-decoration: none;
          color: #1c1e21;
          font-weight: 600;
      }

      .col-form p a:hover {
          text-decoration: underline;
      }
  </style>

  <!DOCTYPE html>
  <html lang="en">
  <center>
      <h3><img src="../images/1.png" class="ok" height="150" width="450"></h3>
  </center>

  <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Email Backup</title>
  </head>

  <body>
      <main>
          <div class="row">
              <div class="col-form">
                  <div class="form-container">
                      <form action="" method="post">
                          <button type="submit" class="button-30 " name="email"><i class="fa fa-envelope-o"></i>SEND</button>
                      </form>
                  </div>
              </div>
          </div>
          </form>
      </main>
  </body>

  </html>